name: CI

on: [push]

env:
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
  BUILD_SCRIPT: npm run generate
  BUILD_SCRIPT_OUTPUT: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        shell: bash
        run: echo "{BRANCH_NAME}={${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build Appliction
        run: $BUILD_SCRIPT
      - name: Log
        run: ls
      # Доставляем собранное приложение на сервер
      - name: copy files via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/home/b/beav1s/sth-edu/public_html"
          strip_components: 1
